### ISSUE TITLE
Rebuild with CustomAction project can delete compiled assemblies

### ISSUE THREAD

**Issue by flcdrg** [wixtoolset/issues#5129]
I have a solution with a number of Wix projects, and a Wix C# custom action project that when built with `msbuild /t:Rebuild` fails.

The problem appears to be that after the custom action project is rebuilt, the setup project (that depends on the custom action project) goes back and cleans the custom action project a second time.

This appears to be similar (if not identical) to the problem outlined in http://stackoverflow.com/questions/18038803/targets-seem-to-be-building-in-the-wrong-order-when-building-wix-custom-action-u

I hope to create a simple repro that I can share.

**Comment by flcdrg** [comment]
FYI I haven't had any success creating a simple repro for this. I have seen that the problem may be related to the use of manually setting project dependencies in the .sln file (via the Project Dependencies dialog in Visual Studio), and the subsequent generation of the .metaproj files by MSBuild.

A possible workaround if you do experience this bug is to build with `/t:Clean;Build` instead of `Rebuild`.

**Comment by flcdrg** [comment]
I have finally managed to create a simple repro (attached)

The problem manifests itself when:
a) a Wix project has manual project dependencies set
b) the custom action project's name causes it to be ordered in the solution file AFTER the wix project.

[CustomAction1.zip](https://github.com/wixtoolset/issues/files/86839/CustomAction1.zip)

**Comment by FishusOne** [comment]
This appears to also affect merge modules.

I have one merge module shared between two installer projects, which have been referenced, and work perfectly well under VS2015. However when built via MSBuild on TeamCity, the reference from the first installer to the merge module is resolved correctly and it is built. However, MSBuild then perfomrs a rebuild on the merge module, but it only goes as far as cleaning the outputs and doesnt actually build the MSM again. Subsequently when the second installer tries to reference the merge module MSBuild expects that since it has already build the merge module, the file is there, and does not build it again. This causes issues when the second installer goes to the linker stage and cannot find the MSM.

Using the workaround proposed by @flcdrg appears to resolve the issue.

**Comment by roslynn** [comment]
still not resolved :(

as @FishusOne said, building in visual studio a *.wixproj outputing merge module is fine but when run via msbuild in the command window (on in the reamcity build, which is effectively the same) it just goes as far as cleaning the project :(

is there an intention to fix it at some point or shall I look for a work around?

**Comment by roslynn** [comment]
Thanks @flcdrg! your suggestion to replace build targets from /t:Rebuild to /t:"Clean;Build" somehow worked for me.

Nevertheless I still think that this bug should be resolved.

**Comment by robmen** [comment]
This issue is open and unassigned. That means it is waiting for someone to investigate the root problem, discuss possible solutions to that problem then implement the decided solution.

If you are interested in doing so yourself, our [developer documentation][devdoc] provides a great checklist for getting started.

If you are not interested then you are waiting for someone else to become interested. If this issue has been open for a long time then there probably isn't much interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[devdoc]: http://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by Onkelborg** [comment]
I think we've stumbled upon this problem recently.

We have a big solution (140+ projects), and among them are ~8 projects directly related to building the installer. We encountered a failed _rebuild_, and I could conclude that:
1. The managed bootstrapper project got built by the Burn project - Target: **Build**
2. The managed bootstrapper project then got built by the solution file - Target: **Rebuild**
3. The Burn project failed since the output from the managed bootstrapper got removed by the second build

I looked into the MSBuild targets files for WiX, and I wonder if they aren't correct. In wix2010.targets:
```xml
  <!--
  ==================================================================================================
  Rebuild

    Delete all intermediate and final build outputs, and then build the project from scratch.
  ==================================================================================================
  -->
  <PropertyGroup>
    <RebuildDependsOn>
      BeforeRebuild;
      Clean;
      $(MSBuildProjectDefaultTargets);
      AfterRebuild;
    </RebuildDependsOn>

    <RebuildDependsOn Condition=" '$(MSBuildProjectDefaultTargets)' == 'Rebuild' ">
      BeforeRebuild;
      Clean;
      Build;
      AfterRebuild;
    </RebuildDependsOn>
  </PropertyGroup>

  <Target
    Name="Rebuild"
    DependsOnTargets="$(RebuildDependsOn)"
    Outputs="$(TargetPath)" />
```

There seems to be an explicit "override" for rebuilds to do a manual clean, and then a build - I guess that this will mess up things..?

I'm not sure, why are these properties redefined at all? And if so, why a separate Clean + Build, why not just a "Rebuild" instead?
