### ISSUE TITLE
ErrorDlg not showing runtime exception

### ISSUE THREAD

**Issue by Rajagurunathan-M007** [wixtoolset/issues#8889]
### WiX Version

4.0.5

### .NET or MSBuild or Visual Studio Version

.NET 8.0.300

### HeatWave Version

1.0.4.5

### Windows Version

Win11 23H2

### Repro Steps

Recently we've migrated to WIX v4. After migration the runtime error are not shown in ErrorDlg popup. 
While we were using WIXv3, the runtime exception was shown in the ErrorDlg popup.

### Actual Result

**In WIX v4, Currently this error is only shown for all kinds of errors like DB script exception, other exceptions, etc...**
![image](https://github.com/user-attachments/assets/2fc8d542-512f-4971-9c1d-7ef8fbd18900)

### Expected Result

**We need to show the runtime error in ErrorDlg as like in WIX v3.**
![image](https://github.com/user-attachments/assets/3cfea9d7-51f8-4474-90ec-cfbb81c601e9)

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by Rajagurunathan-M007** [comment]
Hi @robmen , @barnson , @rseanhall
 Please let us know your suggestions or workaround solutions for the same. It would be really great if you share the solution early as our product release is dependent on this.

Also note we don't have any Custom ErrorDlg, we just use ErrorDlg from wixlib.
Below is our UI code, let me know if you need more details.  **Thanks in advance**

<UI Id="MyWebUI">
      
      <TextStyle Id="WixUI_Font_Normal" FaceName="Tahoma" Size="8" />
      <TextStyle Id="WixUI_Font_Bigger" FaceName="Tahoma" Size="12" />
      <TextStyle Id="WixUI_Font_Title" FaceName="Tahoma" Size="9" Bold="yes" />

      <TextStyle Id="Header" FaceName="Tahoma" Size="10" Red="255" Green="128" Blue="0" Bold="yes" />
      <TextStyle Id="SubHeader" FaceName="Tahoma" Size="8" Red="255" Green="128" Blue="0" />
      <TextStyle Id="ItemHeaderBold" FaceName="Tahoma" Size="8" Red="0" Green="0" Blue="0" Bold="yes" />
      <TextStyle Id="ItemHeaderNormal" FaceName="Tahoma" Size="8" Red="0" Green="0" Blue="0" />
      <TextStyle Id="RedErrorText" FaceName="Tahoma" Size="11" Red="255" Green="99" Blue="71" Bold="no" />
      <TextStyle Id="CustomHeader" FaceName="Segoe UI" Size="14" Bold="no" />
      <TextStyle Id="TextHeader" FaceName="Segoe UI" Size="10" Bold="no" />
      <TextStyle Id="URLTextHeader" FaceName="Tahoma" Size="10" Bold="yes" />
      <TextStyle Id="URLTextStyle" FaceName="Segoe UI" Size="10" Bold="no" Red="241" Blue="121" Green="33" />
      <TextStyle Id="DefaultButtonTextSize" FaceName="Tahoma" Size="10" Bold="no" />
      <TextStyle Id="SmallTextSize" FaceName="Tahoma" Size="10" Bold="no" />
      <TextStyle Id="GreyText" FaceName="Tahoma" Size="10" Red="88" Green="88" Blue="88" Bold="no" />
      <TextStyle Id="SubHeading" FaceName="Tahoma" Size="11" Bold="no" />
      <TextStyle Id="DialogPrimaryStatusDescription" FaceName="Tahoma" Size="12" Red="77" Green="77" Blue="77" Bold="no" />
      <TextStyle Id="LicenseAcceptDescription" FaceName="Tahoma" Size="10" Bold="no" />
      <TextStyle Id="FeatureSelectionTitle" FaceName="Tahoma" Size="11" Bold="no" />
      <TextStyle Id="ReadyInstallSubHeaders" FaceName="Tahoma" Size="11" Bold="no" />
      <TextStyle Id="ReadyInstallTextSize" FaceName="Tahoma" Size="9" Bold="no" />
      <TextStyle Id="ReadyInstallDbSubHeaders" FaceName="Tahoma" Size="10" Bold="no" />
      
      

      <Property Id="DefaultUIFont" Value="WixUI_Font_Normal" />
      <Property Id="WixUI_Mode" Value="InstallDir" />

      <DialogRef Id="BrowseDlg" />
      <DialogRef Id="DiskCostDlg" />
      <DialogRef Id="ErrorDlg" />
      <DialogRef Id="FilesInUse" />
      <DialogRef Id="MsiRMFilesInUse" />
      <DialogRef Id="PrepareDlg" />
      <DialogRef Id="ProgressDlg" />
      <DialogRef Id="ResumeDlg" />
      <DialogRef Id="CustomUserExit" />
      <DialogRef Id="CustomFatalError" />
      <DialogRef Id="PoolSettingsDlg" />
      <DialogRef Id="IISAppPoolStatusDlg" />
      <DialogRef Id="MaintenanceWelcomeDlg" />
      <DialogRef Id="WelcomeDlg" />
      <DialogRef Id="CustomBrowseDlg" />
      <DialogRef Id="CustomWelcomeDlg" />
      <DialogRef Id="CustomLicenseAgreementDlg" />
      <DialogRef Id="CustomDiskUsageDlg" />
      <DialogRef Id="CustomProgressDlg" />
      <DialogRef Id="CustomUserSuccessExit" />
      <DialogRef Id="CustomMaintenanceWelcomeDlg" />
      <DialogRef Id="CustomMaintenanceTypeDlg" />
      
      
      <UIRef Id="WixUI_ErrorProgressText" />

      <ProgressText Message="Initiating Configuration Files Repair" Action="RepairConfigFiles"></ProgressText>
      <ProgressText Message="Initiating BizTalk360 Database Schema Repair" Action="RepairDatabaseSchema"></ProgressText>
      <ProgressText Message="Starting BizTalk360 Monitoring Service" Action="StartMonitoringService"></ProgressText>
      <ProgressText Message="Starting BizTalk360 Analytics Service" Action="StartAnalyticsService"></ProgressText>
       

      
      <Publish Dialog="CustomBrowseDlg" Control="Next" Event="SetTargetPath" Value="INSTALLLOCATION" />
      <Publish Dialog="CustomBrowseDlg" Control="Next" Event="NewDialog" Value="CustomVerifyReadyDlg" Order="3" Condition="((&amp;WebSiteDirFeature=3) OR (&amp;WinServiceDirFreture=3) OR (&amp;WinAnalyticsServiceDirFeature=3) OR (&amp;DatbaseDirFeature=3)) AND 1" />
      
      <Publish Dialog="CustomBrowseDlg" Control="Next" Event="OpenBrowseDialog" Value="FeaturelistSelectionDlg" Order="3" Condition="NOT(&amp;WebSiteDirFeature=3) AND NOT(&amp;WinServiceDirFreture=3) AND NOT(&amp;WinAnalyticsServiceDirFeature=3) AND NOT(&amp;DatbaseDirFeature=3)" />
        <Publish Dialog="CustomBrowseDlg" Control="Back" Event="NewDialog" Value="ConnectionStringDlg" />
      
      <Publish Dialog="CustomVerifyReadyDlg" Control="Back" Event="NewDialog" Value="DefaultUserConfigurationDlg" Order="3" Condition="(&amp;DatbaseDirFeature=3) AND 1" />
      <Publish Dialog="CustomVerifyReadyDlg" Control="Back" Event="NewDialog" Value="CustomBrowseDlg" Order="3" Condition="NOT(&amp;DatbaseDirFeature=3) AND 1" />

      
      <Publish Dialog="CustomMaintenanceWelcomeDlg" Control="Next" Event="NewDialog" Value="CustomMaintenanceTypeDlg" />
      <Publish Dialog="CustomMaintenanceTypeDlg" Control="RepairButton" Event="NewDialog" Value="CustomVerifyReadyDlg" />
      <Publish Dialog="CustomMaintenanceTypeDlg" Control="RemoveButton" Event="NewDialog" Value="CustomVerifyReadyDlg" />
      <Publish Dialog="CustomMaintenanceTypeDlg" Control="Back" Event="NewDialog" Value="CustomMaintenanceWelcomeDlg" />


      <InstallUISequence>
        
        <Show Dialog="WelcomeDlg" Before="ProgressDlg" Overridable="no" Condition="0" />
        <Show Dialog="MaintenanceWelcomeDlg" Before="ProgressDlg" Overridable="no" Condition="0" />
        
        <Show Dialog="CustomWelcomeDlg" Before="ProgressDlg" Condition="NOT Installed OR PATCH" />
        <Show Dialog="CustomProgressDlg" After="ProgressDlg" Overridable="yes" />
        <Show Dialog="CustomMaintenanceWelcomeDlg" Before="ProgressDlg" Overridable="yes" Condition="Installed AND NOT RESUME AND NOT Preselected AND NOT PATCH" />
        <Show Dialog="CustomUserExit" OnExit="cancel" Overridable="yes" />
        <Show Dialog="CustomUserSuccessExit" OnExit="success" Overridable="yes" />
        <Show Dialog="CustomFatalError" OnExit="error" Overridable="yes" />
      </InstallUISequence>
      
      <AdminUISequence>
        <Show Dialog="CustomUserExit" OnExit="cancel" Overridable="yes" />
        <Show Dialog="CustomUserSuccessExit" OnExit="success" Overridable="yes" />
        <Show Dialog="CustomFatalError" OnExit="error" Overridable="yes" />
      </AdminUISequence>
      
    </UI>

**Comment by robmen** [comment]
Hi, @Rajagurunathan-M007, just so your expectations are set correctly, this is an Open Source project. That means it is provided "AS IS" ([see section f of the license](https://wixtoolset.org/docs/about/#microsoft-reciprocal-license-ms-rl)). You are free to dig into the source code and resolve the issue yourself.

If you'd like business guarantees for bug fixes and answers to questions, then you're likely interested in a support contract. [FireGiant offers those](https://www.firegiant.com/services/support-programs/).

**Comment by bevanweiss** [comment]
@Rajagurunathan-M007  are they the same error in both versions? WiX3 vs WiX4?
I ask this, because I can't see any similarity between the error codes, -2147217865 in WiX3, 26204 in WiX4.
If they're different errors, then the whole issue is a bit moot, since it's like complaining that 'To be or not to be" isn't found within a Back Street Boys song... you're simply not comparing the same thing.

It would also be advisable to use WiX5 instead of WiX4.  You will not be getting anything fixed in WiX4.

You should provide the detailed log files for both the WiX3 and WiX4 installations, where the same error is being generated in each version.
And a reproduction repository, which shows the expected behaviour in WiX3, and the unexpected behaviour (for the same scenario) in the latest WiX5 (since as mentioned, WiX4 isn't very meaningful).

**Comment by Rajagurunathan-M007** [comment]
Hi @bevanweiss, As suggested we've migrated our WIX project to WIX 5, but still facing the same issue. Runtime error is not shown in ErrorDlg.

Note: We've tried using v4.0.5 & v5.0.2

Noticed one more behaviour,

1. In WIX v4, If any error occurs the runtime error is logged in Event viewer
2. But In WIX v5, the runtime errors are not logged in Event viewer

Is this is a bug in WIX v4 & v5? Because in WIX v3, we could see the runtime error details in ErrorDlg itself.


![image](https://github.com/user-attachments/assets/b61642e0-5540-4c03-a8bc-cbb6129896bc)

![image](https://github.com/user-attachments/assets/5b45d8d1-28a1-437a-a61c-bbae91a505e0)

![image](https://github.com/user-attachments/assets/0c65778c-3ac1-4121-ace5-71f5e45717d9)

![image](https://github.com/user-attachments/assets/1776b576-8bd5-47be-b0ef-3ccb9e1aeb0f)


**Same error:**

![image](https://github.com/user-attachments/assets/dd6bacad-14df-4af8-901e-3aa7537e9f01)

**Comment by bevanweiss** [comment]
> Hi @bevanweiss, As suggested we've migrated our WIX project to WIX 5, but still facing the same issue. Runtime error is not shown in ErrorDlg.

Where are the detailed log files for the WiX v3 installation, and exactly the same installation scenario when upgraded to WiX v5?
You should also provide a link to a repo which has the project for each of these WiXv3 and WiXv5 installers (minimal reproducible example... https://stackoverflow.com/help/minimal-reproducible-example)

Ensure you enable maximum loggage (if you don't understand /l*vx, then you need to read more)
https://learn.microsoft.com/en-us/windows/win32/msi/command-line-options

And then interpretting the logs yourself is going to be beneficial (after that, you should post them in this Issue)
https://learn.microsoft.com/en-us/windows/win32/msi/windows-installer-logging

**Comment by Rajagurunathan-M007** [comment]
Hi @bevanweiss , @robmen , @barnson As suggested we've tried with Logging option. Still facing the same issue, the runtime error is not logged in MSI log file.

So we've created a sample github repo in WIX v3, v4 & V5.

**Sample WIX repo functionality:** 
To generate SQL error, when we click install in the MSI it will execute a SQL script with Invalid object name to generate SQL error to show in ErrorDlg.
This is the same functionality implemented in all three version repos.


**1) WIX v3 Repo Link:**  https://github.com/Rajagurunathan-M007/WixV3RuntimeError/tree/master/WixV3RuntimeError

In WIX v3, As expected the runtime error is shown in ErrorDlg & runtime error is logged in Event Viewer,

![ErrorDlg](https://github.com/user-attachments/assets/7272630b-222a-468d-a184-eb7515d4986f)

![EventViewer](https://github.com/user-attachments/assets/3cb70556-c136-4775-9b33-b13beb3f6515)



**2) WIX v4 Repo Link:**  https://github.com/Rajagurunathan-M007/WixV4RuntimeError/tree/master/WixV4RuntimeError

But In WIX v4, static error message is shown in ErrorDlg for all kind of errors & runtime error is logged in Event Viewer,

![ErrorDlg](https://github.com/user-attachments/assets/020b95b2-f3f9-49cb-9a7a-da7c7d6d8de0)

![EventViewer](https://github.com/user-attachments/assets/c567bae8-f4ac-4cf8-a6ca-4c758eb1d844)



**3) WIX v5 Repo Link:**  https://github.com/Rajagurunathan-M007/WixV5RuntimeError/tree/master/WixV5RuntimeError

Similarly In WIX v5 also, only static error message is shown in ErrorDlg for all kind of errors & runtime error is logged in Event Viewer,

![ErrorDlg](https://github.com/user-attachments/assets/eb8452e3-48c6-47b7-b209-30b6e0a09665)

![EventViewer](https://github.com/user-attachments/assets/8af2fc65-1a67-4b4f-8f58-afe5d3f354c4)

@bevanweiss - Thanks for your prompt replies, Much appreciated!

Please have a look at these sample repos & let me know if this is a bug in WIX v4. Also Kindly let me know if you need any more details.

Thanks in advance!

**Comment by barnson** [comment]
It is a bug. We'll triage it at next week's online meeting.
